import * as functions from "firebase-functions";
export declare const provisionTenant: functions.HttpsFunction & functions.Runnable<any>;
export declare const bootstrapPlatformAdmin: functions.HttpsFunction & functions.Runnable<any>;
export declare const createStaffUser: functions.HttpsFunction & functions.Runnable<any>;
export declare const deleteStaffUser: functions.HttpsFunction & functions.Runnable<any>;
export declare const enrollDevice: functions.HttpsFunction & functions.Runnable<any>;
export declare const syncNfcUid: functions.CloudFunction<functions.Change<functions.firestore.DocumentSnapshot>>;
export declare const reportFailedLogin: functions.HttpsFunction & functions.Runnable<any>;
export declare const sendPushNotification: functions.CloudFunction<functions.firestore.QueryDocumentSnapshot>;
export declare const alertUnpaidScan: functions.CloudFunction<functions.firestore.QueryDocumentSnapshot>;
